# This is a basic workflow to build robot code.

name: Build Robot Code Tsan

on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2024-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Declares the repository safe and not under dubious ownership.
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Runs a single command using the runners shell
    - name: Compile and run tests on robot code
      run: ./gradlew build -Ptsan

    # Generated the compile_commands.json for clang-tidy
    - name: Generate compile_commands.json
      run: ./gradlew generateCompileCommands

    # Setup wpiformat
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install wpiformat
      run: pip3 install wpiformat

    # Runs clang tidy
    - name: Clang Tidy
      run: wpiformat -no-format -tidy-all -compile-commands=build/compile_commands/linuxathena/