name: Lint and Format

on:
  pull_request:
  push:

jobs:
  wpiformat:
    name: "wpiformat"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Fetch all history and metadata
        run: |
          git config --global --add safe.directory /__w/allwpilib/allwpilib
          git fetch --prune --unshallow
          git checkout -b pr
          git branch -f main origin/main
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install wpiformat
        run: pip3 install wpiformat
      - name: Run
        run: wpiformat
      - name: Check output
        run: git --no-pager diff --exit-code HEAD